import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebar for the separate "Reference" docs instance (generated API + code docs).
// Autogenerated from the website/reference/ tree so OpenAPI and TypeDoc output
// slot in automatically without hand-maintaining entries.
const sidebars: SidebarsConfig = {
  referenceSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
